# Generated by Django 3.2.7 on 2021-09-04 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='支払先名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効?')),
            ],
            options={
                'verbose_name': '支払先',
                'verbose_name_plural': '支払先',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='支払日')),
                ('amount', models.PositiveIntegerField(verbose_name='金額')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='example.payee', verbose_name='支払先')),
            ],
            options={
                'verbose_name': '支払い',
                'verbose_name_plural': '支払い',
            },
        ),
    ]
