# Generated by Django 3.2.7 on 2021-12-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='タスク名')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'TODO'), (1, '完了'), (2, 'キャンセル'), (3, 'WIP')], verbose_name='ステータス')),
            ],
        ),
    ]
